# Generated by Django 2.2 on 2019-04-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Lobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('max_players', models.IntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lobby', to='game_window.Levels')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('ability', models.ManyToManyField(related_name='pokemon', to='game_window.Abilities')),
            ],
        ),
        migrations.CreateModel(
            name='Poke_Rider',
            fields=[
                ('pokemon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_window.Pokemon')),
                ('start_pos', models.IntegerField()),
            ],
            bases=('game_window.pokemon',),
        ),
        migrations.AddField(
            model_name='levels',
            name='enemy',
            field=models.ManyToManyField(related_name='level', to='game_window.Pokemon'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('level', models.IntegerField()),
                ('collected', models.ManyToManyField(related_name='player_c', to='game_window.Pokemon')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_l', to='game_window.Lobbies')),
                ('riding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_r', to='game_window.Poke_Rider')),
            ],
        ),
    ]
