# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-22 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('max_players', models.IntegerField()),
                ('course_map', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poke_Rider',
            fields=[
                ('pokemon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_window.Pokemon')),
                ('start_pos', models.IntegerField()),
            ],
            bases=('game_window.pokemon',),
        ),
        migrations.AddField(
            model_name='player',
            name='collected',
            field=models.ManyToManyField(related_name='player', to='game_window.Pokemon'),
        ),
        migrations.AddField(
            model_name='player',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game_window.Lobbies'),
        ),
    ]
