# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-23 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_window', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lobbies',
            new_name='Lobby',
        ),
    ]
