# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-23 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_window', '0002_auto_20190422_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lobby',
            new_name='Room',
        ),
    ]
